[package]
name = "afterburner-ebpf"
version = "0.1.0"
edition.workspace = true

[dependencies]
aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }
afterburner-common = { workspace = true }
network-types = { workspace = true }

[[bin]]
name = "afterburner"
path = "src/main.rs"